**Step-1: Import packages**

In [59]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

**Step-2: Create a Data Frame using list**

In [60]:
names=['Ramesh','Suresh','Sathish','Mahesh']
# pd.DataFrame(data,index,columns)
pd.DataFrame(names)

         0
0   Ramesh
1   Suresh
2  Sathish
3   Mahesh

**Step-3: I want to change the index**

In [61]:
names=['Ramesh','Suresh','Sathish','Mahesh']
ids=['A','B','C','D']
pd.DataFrame(names,ids)

         0
A   Ramesh
B   Suresh
C  Sathish
D   Mahesh

**Step-4: Add the columns**

In [62]:
names=['Ramesh','Suresh','Sathish','Mahesh']
ids=['A','B','C','D']
cols=['Names']
pd.DataFrame(names,ids,cols)

     Names
A   Ramesh
B   Suresh
C  Sathish
D   Mahesh

**Step-5: Data and columns**

In [35]:
names=['Ramesh','Suresh','Sathish','Mahesh']
cols=['Names']
pd.DataFrame(names,cols)
# here it follows the order of attributes, 
# so here we have given the column names but since 
# no index is given and cols is taken as index
# so in that case we need to give argument name

ValueError: Shape of passed values is (4, 1), indices imply (1, 1)

In [63]:
names=['Ramesh','Suresh','Sathish','Mahesh']
cols=['Names']
pd.DataFrame(names,columns=cols)

     Names
0   Ramesh
1   Suresh
2  Sathish
3   Mahesh

**Step-6: Multiple columns**

In [64]:
names=['Ramesh','Suresh','Sathish']
age=[20,22,24]
pd.DataFrame(names,age)
# pd.DataFrame(data,index)

          0
20   Ramesh
22   Suresh
24  Sathish

In [65]:
names=['Ramesh','Suresh','Sathish']
age=[20,22,24]
cols=['Names','Age']
df=pd.DataFrame(zip(names,age),
                columns=cols)
# pd.DataFrame(data,index)
df

     Names  Age
0   Ramesh   20
1   Suresh   22
2  Sathish   24

**Step-7: Add a new Column to already existing Data Frame**

- In above first we have taken data

- then created a dataframe

- now we want to add new data based on requirement

In [66]:
city=['Hyd','Pune','Blr']
df['City']=city
df

     Names  Age  City
0   Ramesh   20   Hyd
1   Suresh   22  Pune
2  Sathish   24   Blr

In [11]:
df['Marks']=[20,30]
# error : Length of values (2) does not match length of index (3)

ValueError: Length of values (2) does not match length of index (3)

In [12]:
df['Marks']=[20,30,40,50]
# error: Length of values (4) does not match length of index (3)

ValueError: Length of values (4) does not match length of index (3)

In [67]:
df['Marks']=[20,30,40]
df

     Names  Age  City  Marks
0   Ramesh   20   Hyd     20
1   Suresh   22  Pune     30
2  Sathish   24   Blr     40

**Step-8: Update the Column with new values**

In [68]:
df

     Names  Age  City  Marks
0   Ramesh   20   Hyd     20
1   Suresh   22  Pune     30
2  Sathish   24   Blr     40

In [69]:
df['Marks']=[200,300,400]
df

     Names  Age  City  Marks
0   Ramesh   20   Hyd    200
1   Suresh   22  Pune    300
2  Sathish   24   Blr    400

**Step-9: Create empty DataFrame and add the columns**

In [70]:
df1=pd.DataFrame()
df1['Names']=['Ramesh','Suresh','Sathish']
df1['Age']=[20,22,24]
df1['City']=['Hyd','Pune','Blr']
df1

     Names  Age  City
0   Ramesh   20   Hyd
1   Suresh   22  Pune
2  Sathish   24   Blr

**Step-10: Create a DataFrame using Dictionary**

In [71]:
d={'Names':['Ramesh','Suresh','Sathish'],
   'Age':[20,22,24],
   'City':['Hyd','Blr','Pune']}
df2=pd.DataFrame(d)
df2

     Names  Age  City
0   Ramesh   20   Hyd
1   Suresh   22   Blr
2  Sathish   24  Pune

In [72]:
d={'Names':'Ramesh',
   'Age':20,
   'City':'Hyd'}
df2=pd.DataFrame(d)
df2

ValueError: If using all scalar values, you must pass an index

In [73]:
d={'Names':'Ramesh',
   'Age':20,
   'City':'Hyd'}
# give index when giving scalar values
df2=pd.DataFrame(d,index=[0])
df2

    Names  Age City
0  Ramesh   20  Hyd

**Step-11: Save the dataFrame**

In [74]:
# file handling session
# directory//filename.ext
# filename.ext
# we are saving datframes
#   .csv  or  .xlsx

df.to_csv('data.csv')

In [75]:
df.to_excel('datax.xlsx')

In [76]:
df.to_csv(r'D:\misru\NareshIT\Statistics_assignments\data.csv')

**27-11-2025**

**Step-12: Read the DataFrame**

In [77]:
# in order to read the data
# filename.ext
# open(mbox-short.txt).read()
# open(dummy.txt,mode='w').write('hello')

# data.csv   data.xlsx

pd.read_csv('data.csv')

   Unnamed: 0    Names  Age  City  Marks
0           0   Ramesh   20   Hyd    200
1           1   Suresh   22  Pune    300
2           2  Sathish   24   Blr    400

In [78]:
pd.read_excel('datax.xlsx')

   Unnamed: 0    Names  Age  City  Marks
0           0   Ramesh   20   Hyd    200
1           1   Suresh   22  Pune    300
2           2  Sathish   24   Blr    400

In [79]:
df

     Names  Age  City  Marks
0   Ramesh   20   Hyd    200
1   Suresh   22  Pune    300
2  Sathish   24   Blr    400

In [80]:
d={'Names':['Ramesh','Suresh','Sathish'],
   'Age':[20,22,24],
   'City':['Hyd','Blr','Pune']}
df3=pd.DataFrame(d)
df3

     Names  Age  City
0   Ramesh   20   Hyd
1   Suresh   22   Blr
2  Sathish   24  Pune

In [ ]:
df3.to_csv
pd.read_csv

df3.to_csv
pd.read_excel

In [82]:
df3.to_csv('data1.csv',index=False)

In [83]:
pd.read_csv('data1.csv')

     Names  Age  City
0   Ramesh   20   Hyd
1   Suresh   22   Blr
2  Sathish   24  Pune

In [84]:
df3.to_excel('data1.xlsx',index=False)

In [85]:
pd.read_excel('data1.xlsx')

     Names  Age  City
0   Ramesh   20   Hyd
1   Suresh   22   Blr
2  Sathish   24  Pune

In [86]:
# add one more column marks to df3
df3['Marks']=[50,43,49] 
df3

     Names  Age  City  Marks
0   Ramesh   20   Hyd     50
1   Suresh   22   Blr     43
2  Sathish   24  Pune     49

**Step-13: Drop the column**
- labels: 'IndexLabel | None' = None,
    *,
- axis: 'Axis' = 0,
- index: 'IndexLabel | None' = None,
- columns: 'IndexLabel | None' = None,
- level: 'Level | None' = None,
- inplace: 'bool' = False,

In [90]:
# if i want to drop a index
# I need to use index argument name
df3.drop(index=1)

     Names  Age  City  Marks
0   Ramesh   20   Hyd     50
2  Sathish   24  Pune     49

In [88]:
# if i want to drop a column
# I need to use column argument name
df3.drop(columns='Marks')

     Names  Age  City
0   Ramesh   20   Hyd
1   Suresh   22   Blr
2  Sathish   24  Pune

In [89]:
df3.drop(columns=['City','Marks'])

     Names  Age
0   Ramesh   20
1   Suresh   22
2  Sathish   24

In [ ]:
df.drop(index=1)
df.drop(columns='Marks')
# ================================
df.drop('Marks') # if i dont give argument, label
df.drop(1)  # 1 become label
# =======================
# we need to give axis
# axis=0 indicates index
# axis=1 indicates columns

In [91]:
df3.drop('Marks') 
# by default label='marks'
# if you dont mention axis
# by default axis=0====?

KeyError: "['marks'] not found in axis"

In [93]:
df.drop('Marks',axis=1)

     Names  Age  City
0   Ramesh   20   Hyd
1   Suresh   22  Pune
2  Sathish   24   Blr

**inplace**

- when we do the operation the result output is not overwriting

- means the original DataFrame is same as it is.

- in order to do this we need to use **inplace**

- by default inplace= False

- make **inplace=True** if you want to overwrite the result

In [96]:
df.drop('Marks',axis=1,inplace=True)

In [97]:
df

     Names  Age  City
0   Ramesh   20   Hyd
1   Suresh   22  Pune
2  Sathish   24   Blr

**Step-14: Rename the column**

In [99]:
d={'City':'city'}   # {old:new}
#df.rename(<mapper>,<axis>,<inplace>)
df.rename(d,axis=1,inplace=True)
df

     Names  Age  city
0   Ramesh   20   Hyd
1   Suresh   22  Pune
2  Sathish   24   Blr

In [100]:
d={2:'B'}   # {old:new}
#df.rename(<mapper>,<axis>,<inplace>)
df.rename(d,axis=0,inplace=True)
df

     Names  Age  city
0   Ramesh   20   Hyd
1   Suresh   22  Pune
B  Sathish   24   Blr

In [ ]:
## Create one more DF
# x = 1 to 10
# y = square of x
# z = cube of x

In [102]:
x=list(range(1,11))
y=[i*i for i in x]
z=[i**3 for i in x]
df4=pd.DataFrame(zip(x,y,z),columns=['X','Y','Z'])
df4

    X    Y     Z
0   1    1     1
1   2    4     8
2   3    9    27
3   4   16    64
4   5   25   125
5   6   36   216
6   7   49   343
7   8   64   512
8   9   81   729
9  10  100  1000

- len

- shape :  df.shape

- size : df.size

- head : df.head

- tail : df.tail

- isnull : df.isnull

- dtypes : df.dtypes

- info : df.info

In [104]:
len(df4)

10

In [105]:
df4.shape  # 10 rows and 3 columns

(10, 3)

In [106]:
df4.size

30

In [108]:
df4.head()  # first 5

   X   Y    Z
0  1   1    1
1  2   4    8
2  3   9   27
3  4  16   64
4  5  25  125

In [109]:
df4.tail() # last 5

    X    Y     Z
5   6   36   216
6   7   49   343
7   8   64   512
8   9   81   729
9  10  100  1000

In [111]:
df4.isnull() # if null available True else False

       X      Y      Z
0  False  False  False
1  False  False  False
2  False  False  False
3  False  False  False
4  False  False  False
5  False  False  False
6  False  False  False
7  False  False  False
8  False  False  False
9  False  False  False

In [116]:
df4.isnull().sum()

X    0
Y    0
Z    0
dtype: int64

In [113]:
df4.dtypes
# if any categorical columns occures
# it represents as object
# int === int64
# float

X    int64
Y    int64
Z    int64
dtype: object

In [115]:
df4.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   X       10 non-null     int64
 1   Y       10 non-null     int64
 2   Z       10 non-null     int64
dtypes: int64(3)
memory usage: 372.0 bytes

**Step-15: Select a columns**

In [118]:
df4.columns

Index(['X', 'Y', 'Z'], dtype='object')

In [119]:
df4['X']

0     1
1     2
2     3
3     4
4     5
5     6
6     7
7     8
8     9
9    10
Name: X, dtype: int64

In [120]:
l=['X','Y']
df4[l]

    X    Y
0   1    1
1   2    4
2   3    9
3   4   16
4   5   25
5   6   36
6   7   49
7   8   64
8   9   81
9  10  100

In [121]:
df4[['X','Y']]

    X    Y
0   1    1
1   2    4
2   3    9
3   4   16
4   5   25
5   6   36
6   7   49
7   8   64
8   9   81
9  10  100

In [122]:
type(df4['X'])
# 1D
# series ===> no column name

pandas.core.series.Series

In [123]:
type(df4[['X','Y']])
# 2D
# DataFrame ===> column name will be displayed

pandas.core.frame.DataFrame

In [126]:
df4['X'].shape

(10,)

In [125]:
df4[['X','Y']].shape

(10, 2)

In [131]:
df4  # entire Data Frame
df4['Z']  # selecting one particular column
df4['Z'].values # we extracting the data
df4['Z'].values.tolist()

[1, 8, 27, 64, 125, 216, 343, 512, 729, 1000]

In [132]:
df4
df4[['Y','Z']]
df4[['Y','Z']].values.tolist()

[[1, 1],
 [4, 8],
 [9, 27],
 [16, 64],
 [25, 125],
 [36, 216],
 [49, 343],
 [64, 512],
 [81, 729],
 [100, 1000]]